"""v1.0.0

Revision ID: 63c4b349a701
Revises: 28d58a8428a2
Create Date: 2026-01-03 06:31:18.486060+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63c4b349a701'
down_revision: Union[str, None] = '28d58a8428a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先修改 challengequota 表结构
    op.add_column('challengequota', sa.Column('remaining_quota', sa.Integer(), nullable=False))
    op.add_column('challengequota', sa.Column('daily_quota', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_challengequota_user_id'), table_name='challengequota')
    op.drop_column('challengequota', 'quote_remaining')
    # 删除旧主键约束（使用原始 SQL 以支持 if exists）
    op.execute("""
        DO $$ 
        BEGIN
            IF EXISTS (
                SELECT 1 FROM pg_constraint 
                WHERE conname = 'challengequota_pkey' 
                AND conrelid = 'challengequota'::regclass
            ) THEN
                ALTER TABLE challengequota DROP CONSTRAINT challengequota_pkey;
            END IF;
        END $$;
    """)
    op.drop_column('challengequota', 'id')
    # 设置 user_id 为主键
    op.create_primary_key('challengequota_pkey', 'challengequota', ['user_id'])
    
    # 修改 question 表结构
    op.add_column('question', sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='questiondifficulty'), nullable=False))
    op.add_column('question', sa.Column('question_description', sa.String(length=500), nullable=True))
    op.add_column('question', sa.Column('question_content', sa.String(length=10000), nullable=False))
    op.add_column('question', sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('question', sa.Column('correct_option_index', sa.Integer(), nullable=False))
    op.add_column('question', sa.Column('explanation', sa.String(), nullable=False))
    op.drop_column('question', 'content')
    # 最后创建外键（此时 user_id 已经是主键了）
    op.create_foreign_key('fk_question_owner_id', 'question', 'challengequota', ['owner_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先删除外键
    op.drop_constraint('fk_question_owner_id', 'question', type_='foreignkey')
    # 恢复 question 表
    op.add_column('question', sa.Column('content', sa.VARCHAR(length=10000), autoincrement=False, nullable=False))
    op.drop_column('question', 'explanation')
    op.drop_column('question', 'correct_option_index')
    op.drop_column('question', 'options')
    op.drop_column('question', 'question_content')
    op.drop_column('question', 'question_description')
    op.drop_column('question', 'difficulty')
    # 恢复 challengequota 表
    op.drop_constraint('challengequota_pkey', 'challengequota', type_='primary')
    op.add_column('challengequota', sa.Column('id', postgresql.UUID(as_uuid=True), autoincrement=False, nullable=False))
    op.add_column('challengequota', sa.Column('quote_remaining', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_primary_key('challengequota_pkey', 'challengequota', ['id'])
    op.create_index(op.f('ix_challengequota_user_id'), 'challengequota', ['user_id'], unique=True)
    op.drop_column('challengequota', 'daily_quota')
    op.drop_column('challengequota', 'remaining_quota')
    # ### end Alembic commands ###





