"""v1.0.1

Revision ID: d3adf3681d6f
Revises: 63c4b349a701
Create Date: 2026-01-03 07:29:15.481368+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3adf3681d6f'
down_revision: Union[str, None] = '63c4b349a701'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question', 'question_content',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=False)
    # ### end Alembic commands ###





